create table model_line (
  line_id bigint generated by default as identity,
  title text,
  model text,
  year int,
  brand text,
  transmission text,
  drivetype text,
  fueltype text,
  fuelconsumption numeric,
  engine numeric,
  cylindersInEngine numeric,
  bodytype text,
  doors int,
  seats int,

  primary key (line_id)
)

INSERT INTO model_line (title, model, year, brand, transmission, drivetype, fueltype, fuelconsumption, engine, cylindersInEngine, bodytype, doors, seats)
SELECT title, model, year, brand, transmission, "driveType", "fuelType", "fuelConsumption", engine, "cylindersInEngine", "bodyType", doors, seats FROM "CarSales"

create table sales (
  sale_id bigint generated by default as identity,
  suburb text,
  state text,

  primary key (sale_id)
)

insert sales (suburb, state)
SELECT (suburb, state) FROM "CarSales"

create table Car_Sales (
  carsale_id bigint generated by default as identity,
  sale_id int NOT NULL references sales(sale_id),
  model_id int NOT NULL references model_line(line_id),
  custom_id int NOT NULL references custom(custom_id),
  car_id int NOT NULL references cars(car_id),

  primary key (carsale_id)
)

insert into Car_Sales (sale_id, model_id, custom_id, car_id, price)
Select sale_id from sales, union select model_id from model_line, union select custom_id from custom, union select car_id from cars, union select price from "CarSales"